louvre_billetterie:
    resource: "@LouvreBilletterieBundle/Resources/config/routing.yml"
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

payum_all:
    resource: "@PayumBundle/Resources/config/routing/all.xml"
