<?php

namespace Louvre\BilletterieBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BilletRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BilletRepository extends EntityRepository
{
        public function recupReservation($id) {
            $qb = $this->createQueryBuilder('r')
                ->select('r')
                ->where('r.reservation = :pattern')
                ->setParameter('pattern', $id)
            ;
            return $qb->getQuery()->getArrayResult();

        }
}
