<?php

namespace Louvre\BilletterieBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BilletRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BilletRepository extends EntityRepository
{
    // fonction calculant le nombre total de billet pour une date donnée
    public function nombreBilletsPourUneDate($date)
    {
        $qb = $this->createQueryBuilder('b');

        $qb
            ->select('COUNT(b.id)')
            ->leftJoin('b.reservation', 'reservation')
            ->where('reservation.dateReservation = :date')
            ->setParameter('date', $date);

        return $qb->getQuery()->getSingleResult();
    }
}
