<?php

namespace Louvre\BilletterieBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends EntityRepository
{
    public function nombreReservation($date) {
        $qb = $this
            ->createQueryBuilder('r')
            ->where('r.dateReservation = :pattern')
            ->setParameter('pattern', $date)
        ;

        return $qb->getQuery()->getResult();
    }
}
