<?php

namespace Louvre\BilletterieBundle\Repository;

/**
 * TypeTarifRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeTarifRepository extends \Doctrine\ORM\EntityRepository
{
}
