<?php

namespace Louvre\BilletterieBundle\Repository;

/**
 * TypeBilletRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeBilletRepository extends \Doctrine\ORM\EntityRepository
{
}
