# src/Louvre/BilletterieBundle/Ressources/config/routing.yml

louvre_billetterie_homepage:
    path:     /
    defaults: { _controller: LouvreBilletterieBundle:Billet:index }

louvre_billetterie_achat:
    path:    /achat
    defaults: { _controller: LouvreBilletterieBundle:Billet:achat }

louvre_billetterie_achat_paiement:
    path:    /achat/{id}
    defaults: { _controller: LouvreBilletterieBundle:Billet:achat }
    requirements:
        id: '\d+'

louvre_billetterie_achat_paiement_erreur:
    path:    /achat
    defaults: { _controller: LouvreBilletterieBundle:Billet:achat }

louvre_payment_prepare:
    path:    /payment/prepare/{id}
    defaults: { _controller: LouvreBilletterieBundle:Payment:prepare }
    requirements:
        id: '\d+'

louvre_payment_done:
    path:    /payment/done/{id}
    defaults: { _controller: LouvreBilletterieBundle:Payment:done }
    requirements:
        id: '\d+'