services:
    louvre_billetterie.reservation_event_subscriber:
        class: Louvre\BilletterieBundle\EventSubscriber\ReservationEventSubscriber
        arguments: ['@doctrine', '@templating', '@knp_snappy.pdf', '@mailer', '@router']
        tags:
            - {name: kernel.event_subscriber}
