services:
    louvre_billetterie.reservation_event_subscriber:
        class: Louvre\BilletterieBundle\EventSubscriber\ReservationEventSubscriber
        tags:
            - {name: doctrine.event_subscriber}

