services:
    louvre_billetterie.reservation_event_subscriber:
        class: Louvre\BilletterieBundle\EventSubscriber\ReservationEventSubscriber
        arguments: ['@doctrine']
        tags:
            - {name: kernel.event_subscriber}
