services:
    louvre_billetterie.reservation_event_subscriber:
        class: Louvre\BilletterieBundle\EventSubscriber\ReservationEventSubscriber
        arguments: ['@doctrine', '@templating', '@knp_snappy.pdf', '@mailer', '@router']
        tags:
            - {name: kernel.event_subscriber}

    louvre_billetterie.billet_validator:
        class: Louvre\BilletterieBundle\Validator\Constraints\HoraireMaxPMValidator
        tags:
            - {name: validator.constraint_validator}

    louvre_billetterie.reservation_validator:
        class: Louvre\BilletterieBundle\Validator\Constraints\PlafondJournalierBilletsValidator
        arguments: ['@doctrine']
        tags:
            - {name: validator.constraint_validator}


